# Generated by Django 4.2.16 on 2024-11-29 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payments", "0001_initial"),
    ]

    operations = [
        # migrations.CreateModel(
        #     name="ChapaTransaction",
        #     fields=[
        #         (
        #             "id",
        #             models.BigAutoField(
        #                 auto_created=True,
        #                 primary_key=True,
        #                 serialize=False,
        #                 verbose_name="ID",
        #             ),
        #         ),
        #         ("pay_url", models.URLField()),
        #         ("charge_price", models.FloatField(default=0)),
        #         ("amount", models.BigIntegerField(default=0)),
        #         ("is_paid", models.BooleanField(default=False)),
        #         (
        #             "reference_no",
        #             models.CharField(blank=True, max_length=100, null=True),
        #         ),
        #         ("tx_ref", models.CharField(max_length=500)),
        #         (
        #             "user",
        #             models.ForeignKey(
        #                 on_delete=django.db.models.deletion.CASCADE,
        #                 to=settings.AUTH_USER_MODEL,
        #             ),
        #         ),
        #     ],
        # ),
    ]
