# Generated by Django 5.1 on 2024-12-02 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChapaTransaction",
        ),
    ]
