# Generated by Django 5.1 on 2024-12-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="balance",
            field=models.FloatField(default=0.0),
        ),
    ]
