# Generated by Django 4.2 on 2024-12-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_wallet_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game_type', models.CharField(choices=[('10', '10'), ('20', '20'), ('50', '50'), ('100', '100')], max_length=255)),
            ],
        ),
    ]
