# Generated by Django 4.2 on 2025-01-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_selamcoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallethistory',
            name='transaction_type',
            field=models.CharField(choices=[('UPDATE', 'UPDATE'), ('REFERRAL_BONUS', 'REFERRAL_BONUS')], default='UPDATE', max_length=255),
            preserve_default=False,
        ),
    ]
