# Generated by Django 4.2 on 2025-01-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_charge_remove_wallethistory_user_delete_selamcoin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='betAmount',
            field=models.FloatField(default=0.0),
        ),
    ]
