# Generated by Django 4.2 on 2025-01-27 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0013_wintracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wintracker',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='win_tracker', to=settings.AUTH_USER_MODEL),
        ),
    ]
