# Generated by Django 5.1 on 2025-01-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0015_paymentsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("paid", "paid"),
                    ("failed", "failed"),
                ],
                default="paid",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
