# Generated by Django 5.1 on 2025-01-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0016_paymentsession_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentsession",
            name="session_id",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
