# Generated by Django 4.2 on 2025-02-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_alter_paymentsession_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsession',
            name='payment_id',
            field=models.CharField(default='32342q3', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentsession',
            name='reference_no',
            field=models.CharField(default='adsfasdf', max_length=255),
            preserve_default=False,
        ),
    ]
