# Generated by Django 4.2 on 2025-02-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_paymentsession_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsession',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
