# Generated by Django 4.2 on 2025-02-14 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0019_alter_paymentsession_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentsession',
            name='payment_id',
        ),
    ]
