# Generated by Django 4.2 on 2025-06-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0021_depositmessage_alter_paymentsession_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.FloatField(default=20),
        ),
    ]
