# Generated by Django 5.1 on 2024-12-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegramuser",
            name="telegram_id",
            field=models.BigIntegerField(verbose_name="Telegram ID"),
        ),
    ]
