# Generated by Django 5.1 on 2024-12-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_telegramuser_telegram_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramuser",
            name="phone",
            field=models.CharField(blank=True, max_length=32, verbose_name="Phone"),
        ),
    ]
