# Generated by Django 4.2 on 2025-01-26 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_charge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Charge',
        ),
    ]
