# Generated by Django 5.1 on 2025-01-28 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_paymentsession"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PaymentSession",
        ),
    ]
