# Generated by Django 4.2 on 2025-06-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_paymentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='account_number',
            field=models.CharField(default='100034324234', max_length=255),
            preserve_default=False,
        ),
    ]
