# Generated by Django 5.1 on 2024-12-10 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Wallet",
        ),
    ]
